name: Hello Yaml
on:
  push:
    branches: [main]
   
    
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: greets user
        run: echo "Hello from GitHub Actions!" 


