# This is workflow name Hello

name: Hello

on:
  push:
    branches: [main]
    
permissions:
    pages: write      
    id-token: write   
    contents: read
    
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
       -name: say hello to GitHub
       -run: echo "Hello from GitHub Actions!"
       
       -name: Checkout Code 
        uses: actions/checkout@v4 
       -uses: actions/checkout@v4 
    

    
    
